[workspace]
members = [
    "vintage",
    "vintage_blockchain",
    "vintage_consensus",
    "vintage_msg",
    "vintage_network",
    "vintage_state",
    "vintage_utils",
    "vintage_worker",
]
resolver = "2"
