[package]
name = "vintage_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
serde = { version = "1.0.203" }
time = { version = "0.3.36" }
