dev_mode: true
blockchain:
  db_path: vintage2.db
proxy:
  redis_addr: redis://127.0.0.1:6379
node:
  block_interval: 1000
  name: Node2
  listen_addr: 127.0.0.1:8002
  propose_weight: 1
  vote_weight: 1
  peers:
    - name: Node1
      address: 127.0.0.1:8001
      propose_weight: 1
      vote_weight: 1
    - name: Node3
      address: 127.0.0.1:8003
      propose_weight: 1
      vote_weight: 1
    - name: Node4
      address: 127.0.0.1:8004
      propose_weight: 1
      vote_weight: 1