[package]
name = "vintage_msg"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.21" }
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full"]  }
vintage_utils = { path = "../vintage_utils" }
