[package]
name = "vintage_meta_data"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86" }
async-trait = { version = "0.1.80" }
log = { version = "0.4.21" }
rusqlite = {version = "0.31.0", features = ["bundled"] }
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0" }
# vintage
vintage_utils = { path = "../vintage_utils" }
vintage_msg = { path = "../vintage_msg" }
