[package]
name = "vintage_worker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86" }
tokio = { version = "1.38.0" }
# vintage
vintage_msg = { path = "../vintage_msg" }
vintage_blockchain = { path = "../vintage_blockchain" }
