[package]
name = "vintage_consensus"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86" }
# vintage
vintage_msg = { path = "../vintage_msg" }
vintage_network = { path = "../vintage_network" }
